

USE PRIMEIRO_BD

UPDATE CLIENTES
SET EMAIL = 'CONTATO@GMAIL.COM'
WHERE ID_CLIENTE = 1

UPDATE CLIENTES
SET 
	NOME = 'AUGUSTO',
	EMAIL = 'adm.augustocarlos@gmail.com'
WHERE
	ID_CLIENTE = 2

SELECT TOP (1000) [ID_CLIENTE]
      ,[NOME]
      ,[DATA_CADASTRO]
      ,[EMAIL]
  FROM [PRIMEIRO_BD].[dbo].[CLIENTES]

  SELECT * FROM CLIENTES